on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          THIS_PATH="$(realpath "$0")"
          THIS_DIR="$(dirname "$THIS_PATH")"
          # Find all files in THIS_DIR which end in .ino, .cpp, etc., as specified
          # in the regular expression just below
          FILE_LIST="$(find "$THIS_DIR" | grep -E ".*(\.ino|\.cpp|\.c|\.h|\.hpp|\.hh)$")"

          echo -e "Files found to format = \n\"\"\"\n$FILE_LIST\n\"\"\""

          # Format each file.
          # - NB: do NOT put quotes around `$FILE_LIST` below or else the `clang-format` command will 
          #   mistakenly see the entire blob of newline-separated file names as a SINGLE file name instead 
          #   of as a new-line separated list of *many* file names!
          clang-format --verbose -i --style=Google $FILE_LIST
          git add .
          git commit -m "Github Action: Auto format!"
          git push
