on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup git config
        run: |
          git config user.name "github-actions: clang-format"
      - name: Install clang-format
        run: sudo apt install clang-format -y
      - name: Set file_list variable
        run: |
          export FILE_LIST="$(find . | grep -E ".*(\.ino|\.cpp|\.c|\.h|\.hpp|\.hh)$")"
          echo -e "Files found to format = \n\"\"\"\n$FILE_LIST\n\"\"\""
          clang-format --verbose -i --style=Google $FILE_LIST
      - name: commit and push
        run: |
          git add -A
          git config user.name "collie"
          git config user.email colliemst+github@gmail.com
          git commit -m 'Github Action Auto format!'
          git push
